### ISSUE TITLE
7z file extraction killed by zipjail due to clone limit

### ISSUE THREAD

**Issue by phate1** [CAPESandbox/sflock#36]
Hi 
Ive been looking this 7z file:
[14b95edd6f41e96cf8fe2e40e348ac1878b0f7734ed12fd1eabd4916a140328b](https://www.virustotal.com/gui/file/14b95edd6f41e96cf8fe2e40e348ac1878b0f7734ed12fd1eabd4916a140328b)

sflock was failing to unpack it but 7z on the command line was working fine.

Ive found bumping `-c=2` up to `-c=3` [here](https://github.com/CAPESandbox/sflock/blob/master/sflock/abstracts.py#L49) solves the issue.
I've seen that bumping up to 2 weakens the protection due to race conditions. I'm not sure how much more it's weakend going from 2 to 3 or how many files would actually cause this condition.

I can provide full verbose output from zipjail if it is useful, but here is a heavily cut-down version.
clones set to 2:
```
/home/pete/gits/local-lab/venv/lib/python3.8/site-packages/sflock/data/zipjail.elf test.7z /home/pete/tmp/output -v -c=2 -- /usr/bin/7z x -mmt=off -p -o/home/pete/tmp/output test.7z
openat(4294967196, /home/pete/tmp/output/Pasw0rd_2024_With_Setup/Patch.css)
openat(4294967196, /home/pete/tmp/output/Pasw0rd_2024_With_Setup/Patch.css)
clone(0x3d0f00, ...)
clone(0x3d0f00, ...)
clone(0x3d0f00, ...)
clone(0x3d0f00, ...)
clone(0x3d0f00, ...)
Killing child 27491
```

clones set to 3:

```
/home/pete/gits/local-lab/venv/lib/python3.8/site-packages/sflock/data/zipjail.elf test.7z /home/pete/tmp/output -v -c=3 -- /usr/bin/7z x -mmt=off -p -o/home/pete/tmp/output test.7z
futex(94240458351676, 129, 0x7fffffff)
futex(94240458351592, 129, 0x1)
futex(94240458351592, 129, 0x1)
Everything is Ok

Folders: 4
Files: 14
Size:       26974926
Compressed: 9190596
```

**Comment by doomedraven** [comment]
thank you, sorry for delay, i will check tomorrow

**Comment by doomedraven** [comment]
done, thank you
